<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit32e6983f123cc67ff74b21265dc1483b
{
    public static $prefixLengthsPsr4 = array (
        'G' => 
        array (
            'GDText\\Tests\\' => 13,
            'GDText\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'GDText\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/stil/gd-text/tests',
        ),
        'GDText\\' => 
        array (
            0 => __DIR__ . '/..' . '/stil/gd-text/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit32e6983f123cc67ff74b21265dc1483b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit32e6983f123cc67ff74b21265dc1483b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
